Reading files

In [42]:
import pandas as pd

In [56]:
df=pd.read_csv(r'C:\Users\faith\OneDrive\Desktop\Data analysis\Python\Web scrapping\company_revenue_US.csv')

In [57]:
df.head()

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"

In [58]:
df_new=pd.read_excel(r'C:\Users\faith\OneDrive\Desktop\Data analysis\Python\Pandas\Breast.xlsx')

In [47]:
#pd.set_option('display.max.rows',569)
#pd.set_option('display.max.columns',32)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Rank                    100 non-null    int64
 1   Name                    100 non-null    object
 2   Industry                100 non-null    object
 3   Revenue (USD millions)  100 non-null    object
 4   Revenue growth          100 non-null    object
 5   Employees               100 non-null    object
 6   Headquarters            100 non-null    object
dtypes: int64(1), object(6)
memory usage: 5.6+ KB

In [60]:
df.loc[6]

Rank                                                   7
Name                                            Alphabet
Industry                  Technology and cloud computing
Revenue (USD millions)                           350,018
Revenue growth                                     13.9%
Employees                                        183,323
Headquarters                   Mountain View, California
Name: 6, dtype: object

In [61]:
df[df['Rank']<10]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
5,6,Berkshire Hathaway,Conglomerate,"371,433",1.9%,"392,400","Omaha, Nebraska"
6,7,Alphabet,Technology and cloud computing,"350,018",13.9%,"183,323","Mountain View, California"
7,8,Exxon Mobil,Petroleum,"349,595",1.5%,"60,900","Spring, Texas"
8,9,McKesson Corporation,Healthcare,"308,951",11.7%,"48,000","Irving, Texas"

In [62]:
specific_industries=['Technology','Healthcare']
df[df['Industry'].isin(specific_industries)]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
8,9,McKesson Corporation,Healthcare,"308,951",11.7%,"48,000","Irving, Texas"
14,15,Cardinal Health,Healthcare,"226,827",10.6%,"48,411","Dublin, Ohio"
19,20,Elevance Health,Healthcare,"177,011",3.3%,"103,679","Indianapolis, Indiana"
21,22,Meta Platforms,Technology,"164,501",21.9%,"74,067","Menlo Park, California"
22,23,Centene,Healthcare,"163,071",5.9%,"60,500","St. Louis, Missouri"
30,31,Nvidia,Technology,"130,497",114.2%,"36,000","Santa Clara, California"
43,44,Dell Technologies,Technology,"95,567",8.1%,"108,000","Round Rock, Texas"
60,61,HCA Healthcare,Healthcare,"70,603",8.7%,"271,000","Nashville, Tennessee"
83,84,HP,Technology,"53,559",-0.3%,"58,000","Palo Alto, California"
85,86,Intel,Technology,"53,101",-2.1%,"108,900","Santa Clara, California"
86,87,Oracle,Technology,"52,961",6.0%,"159,000","Austin, Texas"
87,88,Broadcom,Technology,"52,432",46.4%,"37,000","Palo Alto, California"
94,95,Ingram Micro Holding,Technology,"47,984",-0.1%,"26,125","Irvine, California"

In [63]:
df[df['Industry'].str.contains('Technology')]

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
6,7,Alphabet,Technology and cloud computing,"350,018",13.9%,"183,323","Mountain View, California"
13,14,Microsoft,Technology and cloud computing,"245,122",15.7%,"228,000","Redmond, Washington"
21,22,Meta Platforms,Technology,"164,501",21.9%,"74,067","Menlo Park, California"
30,31,Nvidia,Technology,"130,497",114.2%,"36,000","Santa Clara, California"
43,44,Dell Technologies,Technology,"95,567",8.1%,"108,000","Round Rock, Texas"
67,68,IBM,Technology and cloud computing,"62,753",1.4%,"284,500","Armonk, New York"
72,73,TD Synnex,Information Technology,"58,452",1.6%,"25,750","Clearwater, Florida"
83,84,HP,Technology,"53,559",-0.3%,"58,000","Palo Alto, California"
85,86,Intel,Technology,"53,101",-2.1%,"108,900","Santa Clara, California"
86,87,Oracle,Technology,"52,961",6.0%,"159,000","Austin, Texas"
87,88,Broadcom,Technology,"52,432",46.4%,"37,000","Palo Alto, California"
94,95,Ingram Micro Holding,Technology,"47,984",-0.1%,"26,125","Irvine, California"

In [67]:
df2=df.set_index('Industry')

In [65]:
df2.filter(items=['Name','Headquarters'],axis=1)

,Name,Headquarters
Industry,,
Retail,Walmart,"Bentonville, Arkansas"
Retail and cloud computing,Amazon,"Seattle, Washington"
Healthcare,UnitedHealth Group,"Minnetonka, Minnesota"
Technology,Apple,"Cupertino, California"
Healthcare,CVS Health,"Woonsocket, Rhode Island"
Conglomerate,Berkshire Hathaway,"Omaha, Nebraska"
Technology and cloud computing,Alphabet,"Mountain View, California"
Petroleum,Exxon Mobil,"Spring, Texas"
Healthcare,McKesson Corporation,"Irving, Texas"
Pharmacy wholesale,Cencora,"Conshohocken, Pennsylvania"
Financials,JPMorgan Chase,"New York City, New York"
Retail,Costco Wholesale,"Issaquah, Washington"
Health insurance,Cigna,"Bloomfield, Connecticut"
Technology and cloud computing,Microsoft,"Redmond, Washington"
Healthcare,Cardinal Health,"Dublin, Ohio"
Petroleum,Chevron,"Houston, Texas"
Financials,Bank of America,"Charlotte, North Carolina"
Automotive,General Motors,"Detroit, Michigan"
Automotive,Ford Motor,"Dearborn, Michigan"
Healthcare,Elevance Health,"Indianapolis, Indiana"
Financials,Citigroup,"New York City, New York"
Technology,Meta Platforms,"Menlo Park, California"
Healthcare,Centene,"St. Louis, Missouri"
Retail,The Home Depot,"Atlanta, Georgia"
Financials,Fannie Mae,"Washington, D.C."
Pharmaceutical,Walgreens Boots Alliance,"Deerfield, Illinois"
Retail,Kroger,"Cincinnati, Ohio"
Petroleum,Phillips 66,"Houston, Texas"
Petroleum,Marathon Petroleum,"Findlay, Ohio"
Telecommunications,Verizon Communications,"New York City, New York"
Technology,Nvidia,"Santa Clara, California"
Financials,Goldman Sachs Group,"New York City, New York"
Financials,Wells Fargo,"San Francisco, California"
Petroleum,Valero Energy,"San Antonio, Texas"
Telecommunications,Comcast,"Philadelphia, Pennsylvania"
Financials,State Farm Insurance,"Bloomington, Illinois"
Conglomerate and telecommunications,AT&T,"Dallas, Texas"
Financials,Freddie Mac,"McLean, Virginia"
Health insurance,Humana,"Louisville, Kentucky"
Financials,Morgan Stanley,"New York City, New York"
Retail,Target,"Minneapolis, Minnesota"
Financials,StoneX Group,"New York City, New York"
Automotive and energy,Tesla,"Austin, Texas"
Technology,Dell Technologies,"Round Rock, Texas"
Beverage,PepsiCo,"Purchase, New York"
Media,Walt Disney,"Burbank, California"
Transportation,United Parcel Service,"Atlanta, Georgia"
Pharmaceutical,Johnson & Johnson,"New Brunswick, New Jersey"
Transportation,FedEx,"Memphis, Tennessee"
Food industry,Archer Daniels Midland,"Chicago, Illinois"
Consumer products manufacturing,Procter & Gamble,"Cincinnati, Ohio"
Retail,Lowe's,"Mooresville, North Carolina"
Petroleum,Energy Transfer Partners,"Dallas, Texas"
Aerospace and defense,RTX,"Arlington County, Virginia"
Retail,Albertsons,"Boise, Idaho"
Food processing,Sysco,"Houston, Texas"
Insurance,Progressive,"Mayfield Village, Ohio"
Financials,American Express,"New York City, New York"
Aerospace and defense,Lockheed Martin,"Bethesda, Maryland"
Financials,MetLife,"New York City, New York"
Healthcare,HCA Healthcare,"Nashville, Tennessee"
Financials,Prudential Financial,"Newark, New Jersey"
Aerospace and defense,Boeing,"Arlington County, Virginia"
Machinery,Caterpillar,"Irving, Texas"
Pharmaceutical industry,Merck,"Kenilworth, New Jersey"
Insurance,Allstate,"Northfield Township, Illinois"
Pharmaceutical industry,Pfizer,"New York City, New York"
Technology and cloud computing,IBM,"Armonk, New York"
Insurance,New York Life Insurance Company,"New York City, New York"
Airline,Delta Air Lines,"Atlanta, Georgia"
Retail,Publix Super Markets,"Lakeland, Florida"
Financials,Nationwide Mutual Insurance Company,"Columbus, Ohio"
Information Technology,TD Synnex,"Clearwater, Florida"
Airline,United Airlines Holdings,"Chicago, Illinois"
Petroleum,ConocoPhillips,"Houston, Texas"
Retail,TJX,"Framingham, Massachusetts"
Pharmaceutical,AbbVie,"Lake Bluff, Illinois"
Petroleum,Enterprise Products Partners,"Houston, Texas"
Telecommunications,Charter Communications,"Stamford, Connecticut"
Food processing,Performance Food Group,"Richmond, Virginia"
Airline,American Airlines Group,"Fort Worth, Texas"
Financials,Capital One Financial,"Tysons, Virginia"
Telecom hardware manufacturing,Cisco Systems,"San Jose, California"
Technology,HP,"Palo Alto, California"
Food processing,Tyson Foods,"Springdale, Arkansas"
Technology,Intel,"Santa Clara, California"
Technology,Oracle,"Austin, Texas"
Technology,Broadcom,"Palo Alto, California"
Agriculture manufacturing,Deere,"Moline, Illinois"
Apparel,Nike,"Beaverton, Oregon"
Insurance,Liberty Mutual Insurance Group,"Boston, Massachusetts"
Petroleum,Plains GP Holdings,"Houston, Texas"
Insurance,USAA,"San Antonio, Texas"
Pharmaceutical,Bristol-Myers Squibb,"New York City, New York"
Technology,Ingram Micro Holding,"Irvine, California"
Aerospace and defense,General Dynamics,"Reston, Virginia"
Beverage,Coca-Cola,"Atlanta, Georgia"
Financials,TIAA,"New York City, New York"
Insurance,Travelers,"New York City, New York"
Pharmaceutical,Eli Lilly,"Indianapolis, Indiana"

In [69]:
df2.loc['Technology']

,Rank,Name,Revenue (USD millions),Revenue growth,Employees,Headquarters
Industry,,,,,,
Technology,4,Apple,"391,035",2.0%,"164,000","Cupertino, California"
Technology,22,Meta Platforms,"164,501",21.9%,"74,067","Menlo Park, California"
Technology,31,Nvidia,"130,497",114.2%,"36,000","Santa Clara, California"
Technology,44,Dell Technologies,"95,567",8.1%,"108,000","Round Rock, Texas"
Technology,84,HP,"53,559",-0.3%,"58,000","Palo Alto, California"
Technology,86,Intel,"53,101",-2.1%,"108,900","Santa Clara, California"
Technology,87,Oracle,"52,961",6.0%,"159,000","Austin, Texas"
Technology,88,Broadcom,"52,432",46.4%,"37,000","Palo Alto, California"
Technology,95,Ingram Micro Holding,"47,984",-0.1%,"26,125","Irvine, California"

In [70]:
df2.iloc[3]

Rank                                          4
Name                                      Apple
Revenue (USD millions)                  391,035
Revenue growth                             2.0%
Employees                               164,000
Headquarters              Cupertino, California
Name: Technology, dtype: object

In [74]:
df[df['Rank']<10].sort_values(by=['Industry','Rank'],ascending=False)

,Rank,Name,Industry,Revenue (USD millions),Revenue growth,Employees,Headquarters
6,7,Alphabet,Technology and cloud computing,"350,018",13.9%,"183,323","Mountain View, California"
3,4,Apple,Technology,"391,035",2.0%,"164,000","Cupertino, California"
1,2,Amazon,Retail and cloud computing,"637,959",11.0%,"1,556,000","Seattle, Washington"
0,1,Walmart,Retail,"680,985",5.1%,"2,100,000","Bentonville, Arkansas"
7,8,Exxon Mobil,Petroleum,"349,595",1.5%,"60,900","Spring, Texas"
8,9,McKesson Corporation,Healthcare,"308,951",11.7%,"48,000","Irving, Texas"
4,5,CVS Health,Healthcare,"372,809",4.2%,"259,500","Woonsocket, Rhode Island"
2,3,UnitedHealth Group,Healthcare,"400,278",7.7%,"400,000","Minnetonka, Minnesota"
5,6,Berkshire Hathaway,Conglomerate,"371,433",1.9%,"392,400","Omaha, Nebraska"